### ISSUE TITLE
Become dedicated API Elements minim package

### ISSUE THREAD

**Issue by kylef** [refractproject/minim-api-description#31]
I am not seeing any benefit from `minim-parse-result` and `minim-api-description` from being a separate package. Sure, theoretically parse result could be use separately but that is never our case. The separation just adds a lot of maintenance overhead for no real world benefit.

I would propose we consume `minim-parse-result` package into this package and rename it to `minim-api-elements`.

/cc @pksunkara @smizell @w-vi

**Comment by smizell** [comment]
My original hope was that there would be a single npm library called API Elements that provided all parsing functionality and that provided an interface to all Minim libraries and adapters. I like this idea because it does move things closer to that. This idea makes sense. 

I think another option would be to move all of these into a monorepo. There is a nice tool called [Lerna](https://github.com/lerna/lerna) that was extracted from Babel to handle this. React and Ember also go this route. I mention this because I don't believe parse results is a bad abstraction, it is just expensive to maintain and hinders evolvability. There isn't much benefit now to have all of these libraries separate n my opinion. Lerna could let you have the best of both worlds.

**Comment by kylef** [comment]
@smizell Ah yes I saw https://github.com/apiaryio/api-elements/issues/17

Okay so what about we instead rename this package to `api-elements` and make it depend on minim which solves https://github.com/apiaryio/api-elements/issues/17.

Would it make sense to move the repository to @apiaryio so that it sits in same org as `api-elements` itself?

**Comment by smizell** [comment]
It's been a while, but I believe the original thought was to have the API Elements library supersedes Fury as the interface to all supported description formats. That library would then return Minim objects based on the results of the parse. 

Up to you all really, just wanted to mention that. If you wanted that route, you could have `api-elements` and `minim-api-elements`. 

I'm also cool with moving the repo to Apiary.

**Comment by w-vi** [comment]
Well it's not gonna be apiaryio but oracle right? Are you cool with that?

**Comment by smizell** [comment]
I think the copyright is already under Apiary, so seems like you should be able to do with it what you please. I'm personally OK with it. My only hope would be that you can simplify the process. I think it's tough with a lot of repos spread across many organizations :)

**Comment by w-vi** [comment]
Yes, the structure is very complicated, one of the things it would be great to simplify.

**Comment by pksunkara** [comment]
I think `api-elements` package should have everything from minim and fury stuff as a single package.

**Comment by kylef** [comment]
Adding an additional packages doesn't contribute to simplifying this structure, just adds more fuel to the fire. This will just add extra unnecessary layers.

Instead of creating a new package that is just a wrapper of the existing libraries let's improve the existing structure.

**Comment by smizell** [comment]
Not trying to push you this direction, but wanted to mention that a monorepo is kind of a hybrid of all of these approaches. You would essentially consolidate all of code for the packages into a single GitHub repo while publishing separate packages in NPM, then deprecate the separate repos. It feels like the problem is not having multiple NPM packages, but having multiple GitHub repos that are dependent on each other.

**Comment by w-vi** [comment]
Monorepo and simplified package structure is IMHO way to go. Too many packages are confusing too.

**Comment by pksunkara** [comment]
Monorepo is at apiaryio/apielements.js
